version: '3.8'

services:
  vault:
    image: vault:latest
    container_name: vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - vault-data:/vault/data
      - ./vault_data:/vault/config
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN:-root}
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    restart: unless-stopped
    networks:
      - vault-network

volumes:
  vault-data:
    driver: local

networks:
  vault-network:
    driver: bridge
