- become: true
  hosts: web_servers
  name: Configure Web Server servers
  tasks:
  - apt:
      cache_valid_time: 3600
      update_cache: true
    name: Update apt cache
  - apt:
      name:
        rocky: &id002
        - nginx
        - certbot
        ubuntu: &id001
        - nginx
        - certbot
      state: present
    name: Install required packages
  - name: Update package cache (Rocky/RHEL)
    when: ansible_os_family == "RedHat"
    yum:
      update_cache: true
  - apt:
      name: *id001
      state: present
    name: Install required packages (Ubuntu)
    when: ansible_os_family == "Debian"
  - name: Install required packages (Rocky)
    when: ansible_os_family == "RedHat"
    yum:
      name: *id002
      state: present
  - name: Start and enable nginx
    systemd:
      enabled: true
      name: nginx
      state: started
  - name: Enable EPEL repository
    yum:
      name: epel-release
      state: present
  - name: Disable SELinux (if needed)
    selinux:
      state: permissive
    when: ansible_selinux.status == "enabled"
  - name: Create nginx config (Rocky)
    template:
      dest: /etc/nginx/nginx.conf
      src: nginx-rocky.conf.j2
    when: ansible_os_family == "RedHat"
  - firewalld:
      permanent: true
      service: http
      state: enabled
    name: Open firewall for HTTP (Rocky)
    when: ansible_os_family == "RedHat"
