---
- name: Install dependencies for python3.12 (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - software-properties-common
      - wget
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Add deadsnakes PPA (Debian/Ubuntu)
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present
  when: ansible_os_family == "Debian"

- name: Install python3.12 (Debian/Ubuntu)
  ansible.builtin.apt:
    name: python3.12
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Set python3.12 as default python3 (Debian/Ubuntu)
  ansible.builtin.shell: |
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 2
  args:
    warn: false
    executable: /bin/bash
  when: ansible_os_family == "Debian"

- name: Install python3 (RedHat/Rocky/CentOS)
  ansible.builtin.yum:
    name:
      - python3
      - wget
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat" 