---
- name: Install dependencies for python3.12 (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - software-properties-common
      - wget
      - openjdk-11-jdk
      - curl
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Add deadsnakes PPA (Debian/Ubuntu)
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present
  when: ansible_os_family == "Debian"

- name: Install python3.12 (Debian/Ubuntu)
  ansible.builtin.apt:
    name: python3.12
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Set python3.12 as default python3 (Debian/Ubuntu)
  ansible.builtin.shell: |
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 2
  args:
    warn: false
    executable: /bin/bash
  when: ansible_os_family == "Debian"

- name: Install Java and dependencies (RedHat/Rocky/CentOS)
  ansible.builtin.yum:
    name:
      - java-11-openjdk-devel
      - wget
      - curl
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

# - name: Create tomcat user
#   ansible.builtin.user:
#     name: tomcat
#     shell: /bin/false
#     home: /opt/tomcat
#     create_home: no

# - name: Download Tomcat
#   ansible.builtin.get_url:
#     url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.108/bin/apache-tomcat-9.0.108.tar.gz
#     dest: /tmp/apache-tomcat-9.0.108.tar.gz
#     mode: '0644'

# - name: Extract Tomcat
#   ansible.builtin.unarchive:
#     src: /tmp/apache-tomcat-9.0.108.tar.gz
#     dest: /opt
#     remote_src: yes
#     creates: /opt/apache-tomcat-9.0.108

# - name: Create Tomcat directory
#   ansible.builtin.file:
#     path: /opt/tomcat
#     state: link
#     src: /opt/apache-tomcat-9.0.108
#     owner: tomcat
#     group: tomcat

# - name: Set Tomcat permissions
#   ansible.builtin.file:
#     path: /opt/tomcat
#     state: directory
#     recurse: yes
#     owner: tomcat
#     group: tomcat

# - name: Create Tomcat systemd service
#   ansible.builtin.template:
#     src: tomcat.service.j2
#     dest: /etc/systemd/system/tomcat.service
#     mode: '0644'

# - name: Start and enable Tomcat
#   ansible.builtin.systemd:
#     name: tomcat
#     state: started
#     enabled: yes
#     daemon_reload: yes