- become: true
  hosts: all
  gather_facts: true
  vars:
    ansible_verbosity: 2
  tasks:
    - name: Ensure Python is available (Rocky/RHEL)
      raw: test -x /usr/bin/python3 || (dnf install -y python3 python3-pip)
      changed_when: false

    - name: Gather facts
      setup:

  roles:
    - "{{ role }}"
